Build translated docs in translated languages

diff --git a/.github/workflows/docs-builder.yml b/.github/workflows/docs-builder.yml
--- a/.github/workflows/docs-builder.yml
+++ b/.github/workflows/docs-builder.yml
@@ -156,7 +156,7 @@ jobs:
           for LANG in $LANGUAGES; do
             echo "Building language: $LANG"
             mkdir -p ./build/html/$DOCS_VERSION/$LANG
-            sphinx-build -c . -D language=$LANG --keep-going en ./build/html/$DOCS_VERSION/$LANG || echo "Build failed for $LANG"
+            sphinx-build -c . -D language=$LANG --keep-going $LANG ./build/html/$DOCS_VERSION/$LANG || echo "Build failed for $LANG"
             test -f ./build/html/$DOCS_VERSION/$LANG/index.html || (echo "Missing index for $LANG" && exit 1)
           done
           touch ./build/html/.nojekyll
